import type { Project } from '@/@types'

export const PROJECTS: Project[] = [
  {
    name: 'Sistema Viver Melhor da ABNMO',
    description:
      'Sistema de gerenciamento e acompanhamento de pacientes da ABNMO.',
    urlGithub: 'https://github.com/ipecode-br/abnmo-frontend',
    urlGithubApi: 'https://github.com/ipecode-br/abnmo-backend',
    image: '/svm_abnmo.jpg',
    stack: [
      'Typescript',
      'React',
      'Next.js 15',
      'Tailwind CSS',
      'Node.js',
      'NestJS',
      'AWS Lambda',
      'AWS SES',
      'TypeORM',
      'MySQL',
      'Jest',
      'Terraform',
    ],
    inProgress: true,
  },
  {
    name: 'Basemaker',
    description:
      'Plataforma de aluguel de audiência segmentadas para Meta Ads.',
    urlPreview: 'https://basemaker.co',
    image: '/basemaker.jpg',
    video: '/basemaker.mp4',
    stack: [
      'Typescript',
      'React',
      'Next.js 15',
      'Material UI',
      'Node.js',
      'Hono',
    ],
  },
  {
    name: 'LiveTrack',
    description:
      'Capture em tempo real os comentários das lives e os SuperChats enviados ao seu canal do YouTube, e salve-os diretamente em uma planilha do Google Sheets ou exporte em formato CSV.',
    urlPreview: 'https://livetrack.julianosill.com.br',
    urlGithub: 'https://github.com/julianosill/livetrack',
    image: '/livetrack-dark.jpg',
    video: '/livetrack.mp4',
    stack: [
      'Google API',
      'React',
      'Next.js 14',
      'Node.js',
      'React Hook Form',
      'Tailwind CSS',
      'shadcn/ui',
    ],
  },
  {
    name: 'Idea Sales',
    description:
      'Sistema sob medida para uma fábrica de móveis local. A aplicação facilita a visualização e análise de desempenho de vendas através de relatórios e gráficos detalhados com diversas estatísticas.',
    image: '/ideasales.jpg',
    stack: [
      'React',
      'Next.js 14',
      'Tanstack Query',
      'Tailwind CSS',
      'shadcn/ui',
      'Chart.js',
      'Jest',
      'PostgreSQL',
    ],
    inProgress: true,
  },
  {
    name: 'Fala que eu te escrevo',
    description:
      'Aplicação web para transcrição de áudios e vídeos integrada à Microsoft Azure AI Speech. Desenvolvida em Next.js 14, utilizando Material UI e conversão de áudio e vídeo utilizando Web Assembly e FFmpeg.',
    urlPreview: 'https://falaqueeuteescrevo.julianosill.com.br',
    urlGithub: 'https://github.com/julianosill/falaqueeuteescrevo',
    image: '/falaqueeuteescrevo.jpg',
    video: '/falaqueeuteescrevo.mp4',
    stack: [
      'React',
      'Next.js 14',
      'Microsoft Azure AI Speech',
      'Material UI',
      'Redux',
      'FFmpeg',
    ],
  },
  {
    name: 'Memonotes',
    description:
      'Aplicação web de gerenciamento notas de texto, com transcrição em tempo real (Speech to Text) e interface acessível. Desenvolvida em Next.js 14, integrando banco de dados Firebase (NoSQL) e autenticação via Google.',
    urlPreview: 'https://memonotes.julianosill.com.br',
    urlGithub: 'https://github.com/julianosill/memonotes',
    image: '/memonotes.jpg',
    video: '/memonotes.mp4',
    stack: [
      'React',
      'Next.js 14',
      'Firebase',
      'Next Auth',
      'OAuth',
      'Tailwind CSS',
      'Radix UI',
      'Framer Motion',
    ],
  },
  {
    name: 'Pizza Shop',
    description:
      'Dashboard para gerenciamento de pedidos de delivery, com gráficos e métricas. Faz uso de cache nas requisições com React Query, reduzindo o uso de recursos da API e melhorando a experiência do usário.',
    urlGithub: 'https://github.com/julianosill/ignite-pizzashop-web',
    urlGithubApi: 'https://github.com/julianosill/bun-pizzashop-api',
    image: '/pizzashop.jpg',
    video: '/pizzashop.mp4',
    stack: [
      'React',
      'React Query',
      'React Hook Form',
      'Vitest',
      'Playwright',
      'MSW',
      'Tailwind CSS',
      'ReCharts',
      'Drizzle ORM',
      'PostgreSQL',
      'Docker',
    ],
  },
]
